[package]
name = "aoc04"
version = "0.1.0"
authors = ["ah6"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
parse-display = "0.4.0"
