[package]
name = "aoc20"
version = "0.1.0"
authors = ["Andrew Henshaw <andy.henshaw@gtri.gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
