[package]
name = "aoc14"
version = "0.1.0"
authors = ["ah6"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = {git = "https://github.com/rust-itertools/itertools.git"} 
regex = "1.4.2"
